# Generated by Django 3.1.5 on 2021-08-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fname')),
                ('lname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lname')),
                ('mname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mname')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='File')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Userdetails',
                'verbose_name_plural': 'Userdetails',
            },
        ),
    ]
